Repository rubyforgood/voices-of-consent, pull requests merged in 2019-11, with the labels that each got.

#345 Update csv import to include user creation
  app/models/volunteer.rb
  db/import_examples/example_volunteer_list.csv
Labels: Hacktoberfest, Type: Feature/Redesign

#373 Add ability to create a new Location from within the volunteers/new form
  app/controllers/locations_controller.rb
  app/javascript/src/components/volunteer-application-form/VolunteerApplicationForm.js
  app/javascript/src/components/volunteer-application-form/university-picker/UniversityPicker.jsx
Labels: First repo contribution

#388 Add hover text to icon with aasm_state
  app/views/box_requests/index.html.erb
Labels: First Ruby for Good contribution, First repo contribution

#389 inventory_tallies seed - partially resolves #274
  db/seeds/dev.rb
Labels: First Ruby for Good contribution, First repo contribution
