Repository rubyforgood/voices-of-consent, pull requests merged in 2019-10, with the labels that each got.

#309 Add researched_at to box_items table, then update it when appropriate
  app/models/box.rb
  db/migrate/20191012012740_add_researched_at_to_box_items.rb
  db/schema.rb
  spec/models/box_spec.rb
Labels: Repo first-timer

#313 Resolve #312: Add content to background.md
  notes/background.md
Labels: First GitHub Contribution, First Ruby for Good contribution, First repo contribution

#314 Update the read me to include troublshooting tips
  README.md
Labels: Type: Documentation

#331 Resolves #329: Removed duplicate 'location_type' field from location form
  app/views/locations/_form.html.erb
Labels: First Ruby for Good contribution, First repo contribution

#325 Create csv upload to upload existing volunteers
  app/controllers/volunteers_controller.rb
  app/models/volunteer.rb
  app/views/volunteers/index.html.erb
  config/routes.rb
Labels: Hacktoberfest, Type: Feature/Redesign

#316 Add more tables to db/seeds/dev.rb [#274]
  app/models/box.rb
  db/seeds/dev.rb
Labels: First Ruby for Good contribution, First repo contribution

#341 Update README.md
  README.md
Labels: First Ruby for Good contribution, First repo contribution

#339 update README.md with seeds.rb credential info
  README.md
Labels: First Ruby for Good contribution, First repo contribution

#356 Make a louder error on /requesters/new when invalid email is input Issue #333
  app/controllers/box_request_triage_controller.rb
  app/javascript/src/components/box-request-form/BoxRequestForm.js
  dump.rdb
  spec/controllers/box_request_triage_controller_spec.rb
Labels: First repo contribution

#366 Resolves #361 - Add box state spec when complete review
  spec/models/box_request_spec.rb
Labels: First Ruby for Good contribution, First repo contribution

#348 Add ok_to_email control to controller and model
  app/models/auto_email_handler.rb
Labels: First Ruby for Good contribution, First repo contribution

#379 [Feature] Show inventory list in alphabetical order based on name
  app/controllers/inventory_types_controller.rb
  spec/controllers/inventory_types_controller_spec.rb
Labels: First Ruby for Good contribution, First repo contribution

#374 [WIP] 310 factory bot traits
  spec/factories/user.rb
  spec/factories/user_permission.rb
  spec/models/box_spec.rb
Labels: First Ruby for Good contribution, First repo contribution
